# @file Migration Template
# @description The template used by Alembic when generating new migration files.

"""add_workflow_types

Revision ID: 1231dcea6fd5
Revises: 1746411b8288
Create Date: 2026-02-12 17:30:04.061354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1231dcea6fd5'
down_revision: Union[str, None] = '1746411b8288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


